### PR TITLE
[12.0][FIX] dms: Remove request website user try

### LINKED ISSUE #42: [12.0] Current user id overwritten by website user (id=4)
Hi there,
i've just installed DMS module and everything works properly at first. But I found something in the code that i cannot understand:
https://github.com/OCA/dms/blob/3a6380e7e93d9365b177c77fa5229f7114777e33/dms/controllers/portal.py#L117
https://github.com/OCA/dms/blob/3a6380e7e93d9365b177c77fa5229f7114777e33/dms/controllers/portal.py#L205

Why current user id (logged user) is overwrite by website user? I mean, whenever I try to access a directory, it throws me an error because user id (4) doesn't have permissions.
As a workaround, the solution is simple:

image

But I would like to know the purpose of that.
Thanks in advance.

### PR DESCRIPTION
**Pull request by victoralmau**
Remove request website user try (it's not necessary).

Fixes #42 

Locked by:

- [x] https://github.com/OCA/dms/pull/47

@Tecnativa TT27782

### CODE REVIEW

**Comment by etobella** [comment]
pre-commit is not right :wink:

**Comment by pedrobaeza** [comment]
@etobella see #47

**Comment by pedrobaeza** [comment]
@victoralmau why are you removing that code for being used when `website` is installed?

**Comment by victoralmau** [comment]
It's not really necessary, if some user try to access some directory or file without permission auto-redirect to home. 
No other addon use it.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
