### PR TITLE
[12.0][IMP] dms: Add URL Attachment

### PR DESCRIPTION
**Pull request by victoralmau**
Add URL Attachment

Superseed: https://github.com/OCA/dms/pull/58

Please @pedrobaeza, @joao-p-marques and @etobella can you review it?

@Tecnativa TT30215

### CODE REVIEW

**Comment by pedrobaeza** [comment]
In my opinion we are mixing concepts: documents shouldn't be URLs. They are very different things. It's not the same as attachments, where you attach something, which can be a link or a document.

This shouldn't be merged IMO.

**Comment by qtiplb** [comment]
Hi @pedrobaeza @victoralmau 

I found this PR while looking exactly for this functionality. We also want to add this to v12 and v14.

The goal is to be able to organize documents (more specifically ir.attachments) in the DMS, regardless of their storage location. I feel this a must for anyone not storing all their documents in Odoo (directly in the filestore or through an object storage).

I would appreciate if you could reconsider so it can stay under the OCA umbrella.

Thanks!

**Comment by pedrobaeza** [comment]
You can extract it to a new module, but not in the main module.

**Comment by qtiplb** [comment]
Alright we'll extract it, do you want us to submit it to OCA/dms ?

**Comment by pedrobaeza** [comment]
Yes, it can be hosted here. The main issue is to maintain such extra code in the main module.

**Pull request closed without merging**
