### PR TITLE
[13.0][FIX] dms: Fix error in portal with access_token

### PR DESCRIPTION
**Pull request by victoralmau**
Fix error in portal with access_token

FWP from 12.0: https://github.com/OCA/dms/pull/85

Please @Yajo and @pedrobaeza can you review it?

It's need to apply in 14.0

@Tecnativa TT29923

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Check pre-commit

**Comment by victoralmau** [comment]
Now, Travis is green.

**Review by yajo — APPROVED** [review]

**Pull request merged**
