### PR TITLE
[MIG] dms_field: Migration to 13.0

### PR DESCRIPTION
**Pull request by albariera**

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Tested the widget and all seemed to work fine. Still missing to test a field relationship, but it seems right for me

**Review by FernandoRomera — APPROVED** [review]

**Comment by etobella** [comment]
Tested the field relationship

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Review by AntoniRomera — APPROVED** [review]

**Pull request merged**
