### PR TITLE
[MIG] dms_field: Migration to 15.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
Standard Migration
Depends on dms(!)
Cherry-pick #170

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
Can you change the license from AGPL to LGPL?. This has already been done in version 13.0 and authorized by the module authors.
https://github.com/OCA/dms/pull/170

**Review by etobella — APPROVED** [review]

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Comment by marylla** [comment]
@olgamarcocb Hi, I wanted to test your migration in runboat but unfortunately I cannot open the form views for Tag, Categories, and the menu "Documents > Documents", because of this error:

<pre>
RangeError: Maximum call stack size exceeded
    at jQuery.extend.jQuery.fn.extend (http://oca-dms-15-0-pr174-ef4de9b2b37d.runboat.odoo-community.org/web/assets/227-9bed6bf/web.assets_common.min.js:1473:720)
    at jQuery.extend.jQuery.fn.extend (http://oca-dms-15-0-pr174-ef4de9b2b37d.runboat.odoo-community.org/web/assets/227-9bed6bf/web.assets_common.min.js:1478:21)
    at jQuery.extend.jQuery.fn.extend (http://oca-dms-15-0-pr174-ef4de9b2b37d.runboat.odoo-community.org/web/assets/227-9bed6bf/web.assets_common.min.js:1478:21)
    at jQuery.extend.jQuery.fn.extend (http://oca-dms-15-0-pr174-ef4de9b2b37d.runboat.odoo-community.org/web/assets/227-9bed6bf/web.assets_common.min.js:1478:21)
    at jQuery.extend.jQuery.fn.extend (http://oca-dms-15-0-pr174-ef4de9b2b37d.runboat.odoo-community.org/web/assets/227-9bed6bf/web.assets_common.min.js:1478:21)
    at jQuery.extend.jQuery.fn.extend (http://oca-dms-15-0-pr174-ef4de9b2b37d.runboat.odoo-community.org/web/assets/227-9bed6bf/web.assets_common.min.js:1478:21)
    at jQuery.extend.jQuery.fn.extend (http://oca-dms-15-0-pr174-ef4de9b2b37d.runboat.odoo-community.org/web/assets/227-9bed6bf/web.assets_common.min.js:1478:21)
    at jQuery.extend.jQuery.fn.extend (http://oca-dms-15-0-pr174-ef4de9b2b37d.runboat.odoo-community.org/web/assets/227-9bed6bf/web.assets_common.min.js:1478:21)
    at jQuery.extend.jQuery.fn.extend (http://oca-dms-15-0-pr174-ef4de9b2b37d.runboat.odoo-community.org/web/assets/227-9bed6bf/web.assets_common.min.js:1478:21)
    at jQuery.extend.jQuery.fn.extend (http://oca-dms-15-0-pr174-ef4de9b2b37d.runboat.odoo-community.org/web/assets/227-9bed6bf/web.assets_common.min.js:1478:21)
</pre>

 I am not sure if this has something to do with your migration but can you have a look at it?
 And it seems that the code coverage is not sufficient. Can you improve it?

**Comment by lijoantony** [comment]
@marylla I have also faced the same issue with `dms_field` module. This issue is caused by the below code in the `setParams` function of file `dms_field/static/src/js/base/dms_tree_controller.js`,

```
this.params = $.extend(
                true,
                {},
                {
                    storage: {
                        domain: storage_domain,
                        context: session.user_context,
                        show: show_storage,
                    },
                    directory: {
                        domain: directory_domain,
                        context: session.user_context,
                        autocompute_directory: autocompute_directory,
                    },
                    file: {
                        domain: [],
                        context: session.user_context,
                        show: true,
                    },
                    initial: undefined,
                },
                params || {}
            );

```

**params || {}** is the issue. I believe the `params`  has some nested cyclic structures which causes the above infinite loop when copy is attempted. I have temporarily fixed this in my code base by commenting out the copying of `params` as below,
```

66,67c70,71
<                 },
<                 params || {}
---
>                 }
>                 //params || {}
```

I don't think the issue is caused by the migration. Probably the `params` structure has changed in odoo 15 which needs to be handled. Somebody more knowledgable can comment on this.

**Comment by etobella** [comment]
True!!! Something happened with it... I removed the parameters, as they obviously have no sense....

**Comment by marylla** [comment]
@etobella @olgamarcocb 
I now can open the menus. So, that is fixed.
And I can also cut and paste files, add new ones and delete them again in Documents View.
But I cannot click "Preview / Download" button in preview section.
I get this error:

<pre>
TypeError: Cannot read properties of undefined (reading 'split')
    at Class._onDMSPreviewFile (http://oca-dms-15-0-pr174-3365331aae1b.runboat.odoo-community.org/web/assets/238-dad2778/web.assets_backend.min.js:9875:943)
    at Class.<anonymous> (http://oca-dms-15-0-pr174-3365331aae1b.runboat.odoo-community.org/web/assets/237-57416fc/web.assets_common.min.js:4850:11)
    at Class.trigger (http://oca-dms-15-0-pr174-3365331aae1b.runboat.odoo-community.org/web/assets/237-57416fc/web.assets_common.min.js:4848:180)
    at Class._trigger_up (http://oca-dms-15-0-pr174-3365331aae1b.runboat.odoo-community.org/web/assets/237-57416fc/web.assets_common.min.js:4854:378)
    at Class._trigger_up (http://oca-dms-15-0-pr174-3365331aae1b.runboat.odoo-community.org/web/assets/237-57416fc/web.assets_common.min.js:4854:462)
    at Class.trigger_up (http://oca-dms-15-0-pr174-3365331aae1b.runboat.odoo-community.org/web/assets/237-57416fc/web.assets_common.min.js:4854:280)
    at Class._onRecordPreview (http://oca-dms-15-0-pr174-3365331aae1b.runboat.odoo-community.org/web/assets/238-dad2778/web.assets_backend.min.js:9892:769)
    at HTMLButtonElement.<anonymous> (http://oca-dms-15-0-pr174-3365331aae1b.runboat.odoo-community.org/web/assets/237-57416fc/web.assets_common.min.js:4850:11)
    at HTMLDivElement.dispatch (http://oca-dms-15-0-pr174-3365331aae1b.runboat.odoo-community.org/web/assets/237-57416fc/web.assets_common.min.js:1783:447)
    at elemData.handle (http://oca-dms-15-0-pr174-3365331aae1b.runboat.odoo-community.org/web/assets/237-57416fc/web.assets_common.min.js:1769:166)
</pre>

Can you please have a look at it?

**Comment by marylla** [comment]
@olgamarcocb @etobella Can you check your PR again, please? :)

**Comment by etobella** [comment]
Sure! It is fixed now. Thanks for the review :smile:

**Comment by marylla** [comment]
@etobella Great, it works now in runboat. No exceptions anymore :)
Can you do something about the test coverage?

**Comment by etobella** [comment]
Sure! I improved test coverage and removed some unnecessary code that was here from some time ago and it was not used.

**Comment by etobella** [comment]
May I ask for a last review in order to be sure that everything works fine @marylla? I made a review locally but some more people checking that all works fine after removing the code would be great :smile:

**Review by marylla — APPROVED** [review]
I tested again in runboat. Works as expected. :+1:

**Pull request merged**
