### PR TITLE
[FIX] dms: custom thumbnail was not correctly computed

### LINKED ISSUE #32: 12.0 : Unable to load picture document
When I try tu upload a picture on a document (to replace the document type icon), I recieve this error :  
```python
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 27

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/fields.py", line 1028, in __get__
    value = record.env.cache.get(record, self)
  File "/.repo_requirements/odoo/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('dms.file(27,).thumbnail', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-12.0/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/dms/dms/models/dms_file.py", line 437, in read
    return super(File, self).read(fields, load=load)
  File "/.repo_requirements/odoo/odoo/models.py", line 2820, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/.repo_requirements/odoo/odoo/models.py", line 5148, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/.repo_requirements/odoo/odoo/fields.py", line 1032, in __get__
    self.determine_value(record)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1145, in determine_value
    self.compute_value(recs)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1099, in compute_value
    self._compute_value(records)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1090, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/build/OCA/dms/dms/models/mixins_thumbnail.py", line 83, in _compute_thumbnail
    record.thumbnail, return_big=True, avoid_resize_medium=True
  File "/.repo_requirements/odoo/odoo/tools/image.py", line 292, in image_get_resized_images
    return_dict[big_name] = image_resize_image_big(base64_source, avoid_if_small=avoid_resize_big, size=size_big)
  File "/.repo_requirements/odoo/odoo/tools/image.py", line 168, in image_resize_image_big
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/.repo_requirements/odoo/odoo/tools/image.py", line 69, in image_resize_image
    image = Image.open(image_stream)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/PIL/Image.py", line 2349, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f64bd4172b0>
```

### PR DESCRIPTION
**Pull request by etobella**
Fixes #32
@pedrobaeza @gregory-moka

### CODE REVIEW

**Comment by etobella** [comment]
This error only happens on 12.0 due to the change of Image fields

**Review by jarroyomorales — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Comment by etobella** [comment]
Fast Tracking as this is an issue /ocabot merge patch

**Comment by pedrobaeza** [comment]
@etobella but I don't really get why I am able to upload a different preview image. Is that intended?

**Comment by etobella** [comment]
That was something existent on the previous module from MuK, we kept it as it was.

**Comment by pedrobaeza** [comment]
OK, it seems a bit weird for me, but it should have its reasons...

**Pull request merged**
