### PR TITLE
Revert "[14.0][FIX] dms: Prevent 200 records limit in search panel."

### PR DESCRIPTION
**Pull request by etobella**
Reverts OCA/dms#180

It is failing, as you can see on the travis action. I think it is probably no longer needed

### CODE REVIEW

**Comment by etobella** [comment]
Fast tracking, as dms is failing

/ocabot merge patch

**Comment by pedrobaeza** [comment]
@victoralmau please check if it's still needed and the patch should be other way

**Comment by victoralmau** [comment]
Sorry, after reviewing this in v14, it is no longer necessary to apply this change.

**Comment by victoralmau** [comment]
Sorry, after reviewing this in v14, it is no longer necessary to apply this change.

**Pull request merged**
