### PR TITLE
[16.0][MIG] dms_auto_classification: Migration to 16.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 16.0

Please @chienandalu and @carolinafernandez-tecnativa can you review it?

@Tecnativa

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
I think something is missing in the wizard view as when you upload the file, the whole raw content shows up as the name...

image

**Comment by victoralmau** [comment]
Fixed, thanks!

**Review by chienandalu — APPROVED** [review]
:+1:

**Review by carolinafernandez-tecnativa — APPROVED** [review]
Functional review LGTM, Thanks :)

**Pull request merged**
