### PR TITLE
[15.0][IMP] dms_auto_classification: Allow users with Documents: User permissions can use the wizard

### PR DESCRIPTION
**Pull request by victoralmau**
Allow users with Documents: User permissions can use the wizard.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT46805

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Doesn't the act_window need to change the group?

**Comment by victoralmau** [comment]
> Doesn't the act_window need to change the group?

The act_window does not currently have any groups set https://github.com/OCA/dms/blob/15.0/dms_auto_classification/wizards/wizard_dms_classification_views.xml#L58

**Comment by pedrobaeza** [comment]
I think the menu and act_window should have them.

**Comment by victoralmau** [comment]
Changes done.

**Review by pedrobaeza — APPROVED** [review]

**Comment by victoralmau** [comment]
Ping @chienandalu

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
