### PR TITLE
[13.0][RFC] dms_field: change license from agpl to lgpl

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Approved by @etobella 
https://github.com/OCA/dms/issues/169

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
@etobella can you restart the pre-commit test please?

**Comment by marcelsavegnago** [comment]
ping @augustodinizl

**Review by augustodinizl — APPROVED** [review]
For me, it's allright

**Review by vanderleiromera — APPROVED** [review]

**Comment by etobella** [comment]
There is a License issue with web_drop_target. Precommit will be solved with #171, but it is failing because web_drop_target is AGPL and DMS (coming from Muk) is LGPL. We need to talk with @hbrunn as originals creator in order to ask for a LICENSE change for web_drop_target or change DMS to AGPL. Last option would be to remove web_drop_target from dms and dms_field and add the functionality on a new AGPL module.

**Comment by hbrunn** [comment]
I'll be fine with a license change, but isn't one of the reasons we do the CLA stuff so that OCA can decide this kind of things on their own? But then I'm not aware of a process to submit such a request to the board, so maybe just asking the other contributors too might be simplest.

**Comment by etobella** [comment]
Yes,OCA might change the LICENSE without asking, but I think it was fine to contact all the affected people in order to avoid conflicts :wink:

**Comment by etobella** [comment]
Can you rebase please?

**Comment by marcelsavegnago** [comment]
> Can you rebase please?

Done

**Pull request merged**
