### PR TITLE
[13.0][FIX] dms: Apply sudo() when downloading the files (portal users do not have access to ir.attachment for example).

### PR DESCRIPTION
**Pull request by victoralmau**
Apply `sudo()` when downloading the files (portal users do not have access to ir.attachment for example).

Please @chienandalu and @pedrobaeza can you review it?

@Tecnativa TT36723

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't this granting access to everyone?

**Comment by victoralmau** [comment]
> Isn't this granting access to everyone?

No, the files are only displayed in the portal if we (the user) have access to the folder that contains them (or with access_token to the folder).

**Review by chienandalu — APPROVED** [review]
I prefer this approach as it relies on the record rules and not in the public link for everyone.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
