### PR TITLE
[14.0] dms: Fix droping and accessing files

### PR DESCRIPTION
**Pull request by etobella**
Adding commits from
#144 and some commits not implemented yet

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Don't you need any change on `web_drop_target` part?

**Comment by etobella** [comment]
Yes, sorry, it depends on https://github.com/OCA/web/pull/2066 I though the PR had been made and it had been mentioned here

**Review by victoralmau — APPROVED** [review]
According to https://github.com/OCA/web/pull/2066, tested locally and it works as expected.

**Pull request merged**
