### PR TITLE
[ADD] German translation (de.po)

### PR DESCRIPTION
**Pull request by Corneliuus**
German translation

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use the translation system accessing through the link in the README (it's https://translation.odoo-community.org/projects/dms-14-0/dms-14-0-dms/) instead of doing a pull request, so that the benefits of such platform can be used. You can upload a whole .po anyways on the platform.

**Comment by Corneliuus** [comment]
I'd like to do it like that but unfortunately, I don't have permissions to create new translations and sending an email to the mentioned address didn't change it.

**Comment by pedrobaeza** [comment]
I have just given you the role of German translator, so you should be now able to translate. @sbidoul isn't nobody monitoring the mail for new translators?

**Comment by sbidoul** [comment]
The mailbox is monitored and processed regularly. @Corneliuus's request arrived only a few hours ago. People must keep in mind OCA is run by volunteers.

**Comment by pedrobaeza** [comment]
Cool, thanks for answering, Stéphane. Next time, I won't forget to ask when they did such request.

**Comment by Corneliuus** [comment]
Thank you @pedrobaeza for giving me the access rights. Sorry, I didn't mean to rush, I supposed that a bot is monitoring the mails and providing the access roles

**Pull request closed without merging**
