### PR TITLE
[13.0][FIX] Update copier template

### PR DESCRIPTION
**Pull request by pedrobaeza**
To avoid interpreter problem.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It doesn't seem to be this...

**Review by rvalyi — APPROVED** [review]

**Comment by pedrobaeza** [comment]
There's seems to be something more.

**Comment by rvalyi** [comment]
last time I got this problem, that was isort that needed an update.

**Comment by pedrobaeza** [comment]
In theory, the latest copier template includes that patches, but the error continues the same.

**Pull request closed without merging**
