### PR TITLE
Explicit access group information

### PR DESCRIPTION
**Pull request by majenkotech**
Add explicit access group creation and usage instructions in the brief getting started instructions.

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Thanks for the changes. You have to perform them on readme/CONFIGURE.rst file instead, and they will be dumped to this file.

Please don't remove the access group part, as it's still relevant.

**Comment by pedrobaeza** [comment]
Thanks. Only one missing thing: can you please squash both commits into one?

**Comment by majenkotech** [comment]
Yeah, I'm just going to nuke the fork and start afresh GH sucks sometimes.

**Comment by pedrobaeza** [comment]
Yes, I never worked directly with GH interface, but use local git, but I admit it complicates a bit the things.

**Pull request closed without merging**
