### PR TITLE
[13.0][IMP] Update copier template

### PR DESCRIPTION
**Pull request by victoralmau**
Update copier template

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I tried this in #239 and it didn't seem enough. Let's see what happens now.

**Comment by HekkiMelody** [comment]
isn't this the infamous isort issue?

https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co

https://github.com/OCA/oca-addons-repo-template/pull/188

Think it was only fixed for v14 and onwards

**Comment by pedrobaeza** [comment]
The isort version change is already reflected in the template for v13: https://github.com/OCA/oca-addons-repo-template/blob/fe5b6f5c35c3d13822d080a9c9e20df209f3a6c5/src/.pre-commit-config.yaml.jinja#L11, but copier is not updating such change. We have already opened an issue in the repository for the same problem: https://github.com/copier-org/copier/issues/1100. Please support it for getting more attention in it.

**Comment by pedrobaeza** [comment]
Manually changed the isort version, so merging.

**Pull request merged**
